# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.cache/wt} [current_project]
set_property parent.project_path {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/divider26.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/ssd_freqdiv.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/onepulse.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/debounce.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/fsm.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/downcounter.v}
  {C:/Users/HP 15/Desktop/digitaldesignnnn/Lab05/lab50201/lab50201.srcs/sources_1/imports/lab501/stopwatch.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top stopwatch -part xc7a35tcpg236-1


write_checkpoint -force -noxdef stopwatch.dcp

catch { report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb }
