# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master.xdc

# IP: ip/blk_mem_gen_font/blk_mem_gen_font.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_font || ORIG_REF_NAME==blk_mem_gen_font} -quiet] -quiet
