set_property SRC_FILE_INFO {cfile:D:/data/logic_design_lab/labs/lab3/lab3_2/lab3_2.srcs/constrs_1/new/lab3_2.xdc rfile:../../../lab3_2.srcs/constrs_1/new/lab3_2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports clk_out]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports rst]
