# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/exp_3.xdc

# IP: ip/KeyboardCtrl_0_1/KeyboardCtrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==KeyboardCtrl_0 || ORIG_REF_NAME==KeyboardCtrl_0} -quiet] -quiet
