# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/flapga-mario_test/flapga-mario_test.cache/wt [current_project]
set_property parent.project_path D:/flapga-mario_test/flapga-mario_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/flapga-mario_test/flapga-mario_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/audio_unit.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/background_engine.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/bcd_7seg.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/bg_rom.hex.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/clock_div.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/cloud_bg.hex.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/display.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/game_engine.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/game_over_text.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/mario.hex.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/mario.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/object_engine.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/ram.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/seg_mux.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/vga_num.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/vga_sync.v
  D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/flapga_mario.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/vga_cons.xdc
set_property used_in_implementation false [get_files D:/flapga-mario_test/flapga-mario_test.srcs/sources_1/new/vga_cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top flapga_mario -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef flapga_mario.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file flapga_mario_utilization_synth.rpt -pb flapga_mario_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
