`define DISP_WIDTH 640
`define DISP_HEIGHT 480

`define CNT_BITS_N 10
`define PX_ADDR_BITS_N 17

`define COLOR_BIT_N 4
`define MEM_DATA_BIT_N 12

`define DEFAULT_COLOR_PIPE `MEM_DATA_BIT_N'h534
`define DEFAULT_COLOR_BIRD `MEM_DATA_BIT_N'h000