// Keyboard
`define KB_ENCODE_BITS_N 9
`define KB_ENCODE_OH_BITS_N 512
`define CODE_SPACE_L `KB_ENCODE_BITS_N'b0_0010_1001
`define CODE_ENTER_L `KB_ENCODE_BITS_N'b0_0101_1010

`define DISP_WIDTH 640
`define DISP_HEIGHT 480

`define CNT_BITS_N 10
`define PX_ADDR_BITS_N 17
`define SCORE_BITS_N 14
`define COLOR_BIT_N 4
`define MEM_DATA_BIT_N 12
`define ALPHABET_BITS_N 8
`define LED_N 16

// States
`define PLAY_STATE 2
`define START_STATE 0
`define END_STATE 1

`define SEGMENT_7_DISPALY_DIGIT_N 4
`define SEGMENT_7_SEGMENT_N 8
`define SEGMENT_7_NONE `SEGMENT_7_SEGMENT_N'b1111111_1
`define SEGMENT_7_EMPTY `SEGMENT_7_SEGMENT_N'b1111111_0
`define RST_OFF 1'b1

// Font map
`define ALPHA_SPACE `ALPHABET_BITS_N'd0
`define ALPHA_EXCLAIM `ALPHABET_BITS_N'd1
`define ALPHA_0 `ALPHABET_BITS_N'd8
`define ALPHA_1 `ALPHABET_BITS_N'd9
`define ALPHA_2 `ALPHABET_BITS_N'd10
`define ALPHA_3 `ALPHABET_BITS_N'd11
`define ALPHA_4 `ALPHABET_BITS_N'd12
`define ALPHA_5 `ALPHABET_BITS_N'd13
`define ALPHA_6 `ALPHABET_BITS_N'd14
`define ALPHA_7 `ALPHABET_BITS_N'd15
`define ALPHA_8 `ALPHABET_BITS_N'd16
`define ALPHA_9 `ALPHABET_BITS_N'd17
`define ALPHA_COLON `ALPHABET_BITS_N'd18
`define ALPHA_A `ALPHABET_BITS_N'd25
`define ALPHA_B `ALPHABET_BITS_N'd26
`define ALPHA_C `ALPHABET_BITS_N'd27
`define ALPHA_D `ALPHABET_BITS_N'd28
`define ALPHA_E `ALPHABET_BITS_N'd29
`define ALPHA_F `ALPHABET_BITS_N'd30
`define ALPHA_G `ALPHABET_BITS_N'd31
`define ALPHA_H `ALPHABET_BITS_N'd32
`define ALPHA_I `ALPHABET_BITS_N'd33
`define ALPHA_J `ALPHABET_BITS_N'd34
`define ALPHA_K `ALPHABET_BITS_N'd35
`define ALPHA_L `ALPHABET_BITS_N'd36
`define ALPHA_M `ALPHABET_BITS_N'd37
`define ALPHA_N `ALPHABET_BITS_N'd38
`define ALPHA_O `ALPHABET_BITS_N'd39
`define ALPHA_P `ALPHABET_BITS_N'd40
`define ALPHA_Q `ALPHABET_BITS_N'd41
`define ALPHA_R `ALPHABET_BITS_N'd42
`define ALPHA_S `ALPHABET_BITS_N'd43
`define ALPHA_T `ALPHABET_BITS_N'd44
`define ALPHA_U `ALPHABET_BITS_N'd45
`define ALPHA_V `ALPHABET_BITS_N'd46
`define ALPHA_W `ALPHABET_BITS_N'd47
`define ALPHA_X `ALPHABET_BITS_N'd48
`define ALPHA_Y `ALPHABET_BITS_N'd49
`define ALPHA_Z `ALPHABET_BITS_N'd50

// Music Control
`define MUSIC_ADDR_BITS_N 10
`define MUSIC_DATA_BITS_N 22
//`define MUSIC_CNT_BITS_N 10
`define MUSIC_CNT_LIMIT 1024
`define SONG_ID_BITS_N 4

`define FRUIT_PUDDING_SONG_ID 'd0
`define ANGRY_BIRD_SONG_ID 'd1
`define FLAP_SONG_ID 'd2
`define BUMP_SONG_ID 'd3
`define NONE_SONG_ID 'd4

`define FRUIT_PUDDING_CNT_LIMIT 340
`define ANGRY_BIRD_CNT_LIMIT 313
`define FLAP_CNT_LIMIT 2
`define BUMP_CNT_LIMIT 12