`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2022/06/05 17:55:30
// Design Name: 
// Module Name: spk
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

module fruit_pudding_mem #(
    parameter MUSIC_ADDR_BITS_N = 0,
    parameter MUSIC_DATA_BITS_N = 0
)(
    input rst_n,
    input [MUSIC_ADDR_BITS_N-1:0] addr,
    output reg [MUSIC_DATA_BITS_N-1:0] data
);

    localparam none = 22'd11;
    localparam m_do = 22'd382219;
    localparam m_re_b = 22'd360776;
    localparam m_re = 22'd340529;
    localparam m_mi_b = 22'd321409;
    localparam m_mi = 22'd303370;
    localparam m_fa = 22'd286344;
    localparam m_so_b = 22'd270272;
    localparam m_so = 22'd255102;
    localparam m_la_b = 22'd240789;
    localparam m_la = 22'd227272;
    localparam m_si_b = 22'd214518;
    localparam m_si = 22'd202429;
    localparam h_do = 22'd190839;
    localparam h_re_b = 22'd180384;
    localparam h_re = 22'd170068;
    localparam h_mi_b = 22'd160707;
    localparam h_mi = 22'd151515;
    localparam h_fa = 22'd143266;
    localparam h_so_b = 22'd12536;
    localparam h_so = 22'd127551;
    localparam h_la_b = 22'd120393;
    localparam h_la = 22'd113636;
    localparam h_si_b = 22'd107258;
    localparam h_si = 22'd101214;
    
    always@(*)begin
        case (addr)
            // 'd0: data = none;//row_subsection
            // 'd1: data = none;
            // 'd2: data = none;//2_1
            'd0: data = h_fa;
            'd1: data = h_fa;
            'd2: data = h_re;

            'd3: data = h_fa;
            'd4: data = h_fa;	
            'd4: data = none;
            'd5: data = h_re;
            'd6: data = h_re;
            'd7: data = none;
            'd8: data = h_re;
            'd9: data = h_re;
            'd10: data = none;
            'd11: data = h_re;
            'd12: data = h_re;
            'd13: data = none;
            'd14: data = h_re;
            'd15: data = h_re;
            'd16: data = none;//2_2
            'd17: data = h_so;
            'd18: data = h_so;
            'd19: data = none;
            'd20: data = h_re;
            'd21: data = h_re;
            'd22: data = none;
            'd23: data = h_re;
            'd24: data = h_re;
            'd25: data = none;
            'd26: data = h_re;
            'd27: data = h_re;
            'd28: data = none;
            'd29: data = h_re;
            'd30: data = h_re;
            'd31: data = none;//2_3
            'd32: data = h_fa;
            'd33: data = h_fa;
            'd34: data = none;
            'd35: data = h_re;     
            'd36: data = h_re;
            'd37: data = none;
            'd38: data = h_re;
            'd39: data = h_re;
            'd40: data = none;
            'd41: data = h_re;
            'd42: data = h_re;
            'd43: data = none;
            'd44: data = h_re;
            'd45: data = h_re;
            'd46: data = none;//2_4
            'd47: data = h_mi;
            'd48: data = h_mi;
            'd49: data = none;
            'd50: data = m_la;
            'd51: data = m_la;
            'd52: data = none;
            'd53: data = m_la;
            'd54: data = m_la;
            'd55: data = none;
            'd56: data = m_la;
            'd57: data = m_la;
            'd58: data = none;
            'd59: data = m_la;
            'd60: data = m_la;
            'd61: data = none;//3_1
            'd62: data = h_fa;
            'd63: data = h_fa;
            'd64: data = none;
            'd65: data = h_re;
            'd66: data = h_re;
            'd67: data = none;
            'd68: data = h_re;
            'd69: data = h_re;
            'd70: data = none;
            'd71: data = h_re;
            'd72: data = h_re;
            'd73: data = none;
            'd74: data = h_re;
            'd75: data = h_re;
            'd76: data = none;//3_2
            'd77: data = h_la;
            'd78: data = h_la;
            'd79: data = none;
            'd80: data = h_re;
            'd81: data = h_re;
            'd82: data = none;
            'd83: data = h_re;
            'd84: data = h_re;
            'd85: data = none;
            'd86: data = h_re;
            'd87: data = h_re;
            'd88: data = none;
            'd89: data = h_re;
            'd90: data = h_re;
            'd91: data = none;//3_3
            'd92: data = h_la;
            'd93: data = h_la;
            'd94: data = none;
            'd95: data = h_re;
            'd96: data = h_re;
            'd97: data = none;
            'd98: data = h_re;
            'd99: data = h_re;   
            'd100: data = none;
            'd101: data = h_re;
            'd102: data = h_re;     
            'd103: data = none;
            'd104: data = h_re;
            'd105: data = h_re;
            'd106: data = none;//3_4
            'd107: data = h_re;
            'd108: data = h_re;
            'd109: data = none;
            'd110: data = h_mi;
            'd111: data = h_mi;
            'd112: data = none;
            'd113: data = h_fa;
            'd114: data = h_fa;
            'd115: data = none;
            'd116: data = h_so;
            'd117: data = h_so;
            'd118: data = none;
            'd119: data = h_fa;
            'd120: data = h_fa;
            'd121: data = none;
            'd122: data = h_mi;
            'd123: data = h_mi;
            'd124: data = none;
            'd125: data = h_re;
            'd126: data = h_re;
            'd127: data = none;
            'd128: data = h_mi;
            'd129: data = h_mi;
            'd130: data = none;//4_1
            'd131: data = h_fa;
            'd132: data = h_fa;
            'd133: data = none;
            'd134: data = h_re;
            'd135: data = h_re;     
            'd136: data = none;
            'd137: data = h_re;
            'd138: data = h_re;
            'd139: data = none;
            'd140: data = h_re;
            'd141: data = h_re;
            'd142: data = none;
            'd143: data = h_re;
            'd144: data = h_re;
            'd145: data = none;//4_2
            'd146: data = h_so;
            'd147: data = h_so;
            'd148: data = none;
            'd149: data = h_re;
            'd150: data = h_re;
            'd151: data = none;
            'd152: data = h_re;
            'd153: data = h_re;
            'd154: data = none;
            'd155: data = h_re;
            'd156: data = h_re;
            'd157: data = none;
            'd158: data = h_re;
            'd159: data = h_re;
            'd160: data = none;//4_3
            'd161: data = h_fa;
            'd162: data = h_fa;
            'd163: data = none;
            'd164: data = h_re;
            'd165: data = h_re;
            'd166: data = none;
            'd167: data = h_re;
            'd168: data = h_re;
            'd169: data = none;
            'd170: data = h_re;
            'd171: data = h_re;
            'd172: data = none;
            'd173: data = h_re;
            'd174: data = h_re;
            'd175: data = none;//4_4
            'd176: data = h_mi;
            'd177: data = h_mi;
            'd178: data = none;
            'd179: data = m_la;
            'd180: data = m_la;
            'd181: data = none;
            'd182: data = m_la;
            'd183: data = m_la;
            'd184: data = none;
            'd185: data = m_la;
            'd186: data = m_la;
            'd187: data = none;
            'd188: data = m_la;
            'd189: data = m_la;
            'd190: data = none;//5_1
            'd191: data = h_fa;
            'd192: data = h_fa;
            'd193: data = none;
            'd194: data = h_re;
            'd195: data = h_re;
            'd196: data = none;
            'd197: data = h_re;
            'd198: data = h_re;
            'd199: data = none;
            'd200: data = h_re;
            'd201: data = h_re;
            'd202: data = none;
            'd203: data = h_re;
            'd204: data = h_re;
            'd205: data = none;//5_2
            'd206: data = h_la;
            'd207: data = h_la;
            'd208: data = none;
            'd209: data = h_re;
            'd300: data = h_re;
            'd301: data = none;
            'd302: data = h_re;
            'd303: data = h_re;
            'd304: data = none;
            'd305: data = h_re;
            'd306: data = h_re;
            'd307: data = none;
            'd308: data = h_re;
            'd309: data = h_re;
            'd310: data = none;//5_3
            'd311: data = h_la;
            'd312: data = h_la;
            'd313: data = none;
            'd314: data = h_re;
            'd315: data = h_re;
            'd316: data = none;
            'd317: data = h_re;
            'd318: data = h_re;
            'd319: data = none;
            'd311: data = h_re;
            'd312: data = h_re;   
            'd313: data = none;
            'd314: data = h_re;
            'd315: data = h_re;
            'd316: data = none;//5_4
            'd317: data = h_re;
            'd318: data = h_re;
            'd319: data = none;
            'd320: data = h_mi;
            'd321: data = h_mi;
            'd322: data = none;
            'd323: data = h_fa;
            'd324: data = h_fa;
            'd325: data = none;
            'd326: data = h_so;
            'd327: data = h_so;
            'd328: data = none;
            'd329: data = h_fa;
            'd330: data = h_fa;
            'd331: data = none;
            'd332: data = h_mi;
            'd333: data = h_mi;
            'd334: data = none;
            'd335: data = h_re;
            'd336: data = h_re;
            'd337: data = none;
            'd338: data = h_mi;
            'd339: data = h_mi;
            // 'd340: data = none;  
        default:
            data = 'd0;
    endcase
    //    case (addr)
    //        'd0: data = none;
    //        'd1: data = none;
    //        'd2: data = none;
    //         'd3: data = m_mi;
    //    //     'd4: data = none;
    //         'd5: data = m_la;
    //    //     'd6: data = none;
    //         'd7: data = m_si;
    //    //     'd8: data = none;
    //         'd9: data = h_do;
    //         'd10: data = h_do;
    //    //     'd11: data = none;
    //         'd12: data = h_do;
    //    //     'd13: data = none;
    //         'd14: data = h_re;
    //    //     'd15: data = none;
    //         'd16: data = m_si;
    //         'd17: data = m_si;
    //    //     'd18: data = none;
    //         'd19: data = m_si;
    //    //     'd20: data = none;
    //         'd21: data = h_do;
    //    //     'd22: data = none;
    //         'd23: data = m_la;
    //         'd24: data = m_la;
    //         'd25: data = m_la;
    //         'd26: data = m_la;
    //    //     'd27: data = none;
    //         'd28: data = m_la;
    //    //     'd29: data = none;
    //         'd30: data = m_si;
    //    //     'd31: data = none;
    //         'd32: data = h_do;
    //    //     'd33: data = none;
    //         'd34: data = h_re;
    //    //     'd35: data = none;
            
    //         'd36: data = h_mi;
    //         'd37: data = h_mi;
    //    //     'd38: data = none;
    //         'd39: data = h_mi;
    //         'd40: data = h_mi;
    //    //     'd41: data = none;
    //         'd42: data = h_mi;
    //         'd43: data = h_mi;
    //    //     'd44: data = none;
    //         'd45: data = h_mi;
    //         'd46: data = h_mi;
    //    //     'd47: data = none;
    //         'd48: data = h_mi;
    //         'd49: data = h_mi;
    //         'd50: data = h_mi;
    //         'd51: data = h_mi;
    //         'd52: data = h_mi;
    //         'd53: data = h_mi;
    //    //     'd54: data = none;
    //         'd55: data = h_re;
    //    //     'd56: data = none;
    //         'd57: data = h_mi;
    //    //     'd58: data = none;
    //         'd59: data = h_fa;
    //         'd60: data = h_fa;
    //         'd61: data = h_fa;
    //         'd62: data = h_fa;
    //    //     'd63: data = none;
    //         'd64: data = m_si;
    //         'd65: data = m_si;
    //    //     'd66: data = none;
    //         'd67: data = h_do;
    //    //     'd68: data = none;
    //         'd69: data = h_re;
    //    //     'd70: data = none;
    //         'd71: data = h_mi;
    //         'd72: data = h_mi;
    //         'd73: data = h_mi;
    //         'd74: data = h_mi;
    //    //     'd75: data = none;
    //         'd76: data = m_la;
    //         'd77: data = m_la;
    //    //     'd78: data = none;
    //         'd79: data = m_la;
    //    //     'd80: data = none;
    //         'd81: data = m_si;
    //    //     'd82: data = none;
    //         'd83: data = h_do;
    //         'd84: data = h_do;
    //    //     'd85: data = none;
    //         'd86: data = h_do;
    //    //     'd87: data = none;
    //         'd88: data = h_re;
    //    //     'd89: data = none;
    //         'd90: data = m_si;
    //         'd91: data = m_si;
    //    //     'd92: data = none;
    //         'd93: data = m_si;
    //    //     'd94: data = none;
    //         'd95: data = h_do;
    //    //     'd96: data = none;
    //         'd97: data = m_la;
    //         'd98: data = m_la;
    //         'd99: data = m_la;
            
    //         'd100: data = m_la;
    //         'd101: data = m_la;
    //    //     'd102: data = none;
            
            
    //         'd103: data = m_mi;
    //    //     'd104: data = none;
    //         'd105: data = m_la;
    //    //     'd106: data = none;
    //         'd107: data = m_si;
    //    //     'd108: data = none;
    //         'd109: data = h_do;
    //         'd110: data = h_do;
    //    //     'd111: data = none;
    //         'd112: data = h_do;
    //    //     'd113: data = none;
    //         'd114: data = h_re;
    //    //     'd115: data = none;
    //         'd116: data = m_si;
    //         'd117: data = m_si;
    //         'd118: data = m_si;
    //         'd119: data = m_si;
    //    //     'd120: data = none;
    //         'd121: data = h_do;
    //    //     'd122: data = none;
    //         'd123: data = m_la;
    //         'd124: data = m_la;
    //         'd125: data = m_la;
    //         'd126: data = m_la;
    //    //     'd127: data = none;
    //         'd128: data = m_la;
    //    //     'd129: data = none;
    //         'd130: data = m_si;
    //    //     'd131: data = none;
    //         'd132: data = h_do;
    //    //     'd133: data = none;
    //         'd134: data = h_re;
    //    //     'd135: data = none;
            
    //         'd136: data = h_mi;
    //         'd137: data = h_mi;
    //    //     'd138: data = none;
    //         'd139: data = h_mi;
    //         'd140: data = h_mi;
    //    //     'd141: data = none;
    //         'd142: data = h_mi;
    //         'd143: data = h_mi;
    //    //     'd144: data = none;
    //         'd145: data = h_mi;
    //         'd146: data = h_mi;
    //    //     'd147: data = none;
    //         'd148: data = h_mi;
    //         'd149: data = h_mi;
    //         'd150: data = h_mi;
    //         'd151: data = h_mi;
    //         'd152: data = h_mi;
    //         'd153: data = h_mi;
    //    //     'd154: data = none;
    //         'd155: data = h_re;
    //    //     'd156: data = none;
    //         'd157: data = h_mi;
    //    //     'd158: data = none;
    //         'd159: data = h_fa;
    //         'd160: data = h_fa;
    //         'd161: data = h_fa;
    //         'd162: data = h_fa;
    //    //     'd163: data = none;
    //         'd164: data = m_si;
    //         'd165: data = m_si;
    //    //     'd166: data = none;
    //         'd167: data = h_do;
    //    //     'd168: data = none;
    //         'd169: data = h_re;
    //    //     'd170: data = none;
    //         'd171: data = h_mi;
    //         'd172: data = h_mi;
    //         'd173: data = h_mi;
    //         'd174: data = h_mi;
    //    //     'd175: data = none;
    //         'd176: data = m_la;
    //         'd177: data = m_la;
    //    //     'd178: data = none;
    //         'd179: data = m_la;
    //    //     'd180: data = none;
    //         'd181: data = m_si;
    //    //     'd182: data = none;
    //         'd183: data = h_do;
    //         'd184: data = h_do;
    //    //     'd185: data = none;
    //         'd186: data = h_do;
    //    //     'd187: data = none;
    //         'd188: data = h_re;
    //    //     'd189: data = none;
    //         'd190: data = m_si;
    //         'd191: data = m_si;
    //    //     'd192: data = none;
    //         'd193: data = m_si;
    //    //     'd194: data = none;
    //         'd195: data = h_do;
    //    //     'd196: data = none;
    //         'd197: data = m_la;
    //         'd198: data = m_la;
    //         'd199: data = m_la;
    //         'd200: data = m_la;
    //         'd201: data = m_la;
    //    //     'd202: data = none;
    //      default:
    //          data = 22'd0;
    //  endcase
    end
      
endmodule

