# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/data/logic_design_lab/final_project/final/final.srcs/sources_1/ip/blk_mem_gen_bg_big/blk_mem_gen_bg_big.xci
# IP: The module: 'blk_mem_gen_bg_big' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/data/logic_design_lab/final_project/final/final.srcs/sources_1/ip/blk_mem_gen_bg_big/blk_mem_gen_bg_big_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_bg_big'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/data/logic_design_lab/final_project/final/final.srcs/sources_1/ip/blk_mem_gen_bg_big/blk_mem_gen_bg_big.xci
# IP: The module: 'blk_mem_gen_bg_big' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/data/logic_design_lab/final_project/final/final.srcs/sources_1/ip/blk_mem_gen_bg_big/blk_mem_gen_bg_big_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_bg_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
